/* Text editor types */
const CHANGE_STATE_POST = "CHANGE_STATE_POST";
const CHANGE_TAGS_POST = "CHANGE_TAGS_POST";
const CHANGE_CONTENT_POST = "CHANGE_CONTENT_POST";
const CHANGE_IMAGE_POST = "CHANGE_IMAGE_POST";
const REQUEST_CREATE_POST = "REQUEST_CREATE_POST";
const SUCCESS_CREATE_POST = "SUCCESS_CREATE_POST";
const ERROR_CREATE_POST = "ERROR_CREATE_POST";
const IS_LOGIN = "IS_LOGIN";
const IS_LOGOUT = "IS_LOGOUT";

export {
  CHANGE_STATE_POST,
  CHANGE_TAGS_POST,
  CHANGE_CONTENT_POST,
  CHANGE_IMAGE_POST,
  REQUEST_CREATE_POST,
  SUCCESS_CREATE_POST,
  ERROR_CREATE_POST,
  IS_LOGIN,
  IS_LOGOUT,
};
